spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: 12345
  batch:
    initialize-schema: always
    job:
      enabled: false
  jackson:
    serialization:
      indent_output: true
  profiles:
    active: dev

resource:
  folder: /Users/anveshgatadi/Data/code/java/assignment/src/main/resources/data

